- name: apt update
  apt:
    update_cache: yes

- name: Squid Install
  apt:
    name: squid
    state: latest

- name: squid.conf 転送
  copy:
    src: squid.conf
    dest: /etc/squid/

- name: Squidサービス再起動処理
  service:
    name: squid
    state: restarted